/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import runner.Runner;

public class App {
    public static void main(String[] args) {
        Runner rn = new Runner();
        rn.run();
    }
}
