/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;

import bot.Bot;

public class App {
    public static void main(String[] args) throws IOException {
        new Bot();
    }
}
